Us17 feedback para usuarios
fga-eps-mds/2019.1-MaisMonitoria-FrontEnd pull request #19
Opened 2019-05-20 18:14 UTC by MatheusEstanislau

## Issue resolvida

[[US17] Feedback Para Usuários](https://github.com/fga-eps-mds/2019.1-MaisMonitoria/issues/129)

## Comentário

Foram adicionados feedbacks de sucesso e falha para o usuário nas páginas Login, SignUp, EditProfile e RegisterMonitoring. 

Na pagina Login foram acrescentados feedbacks para melhor comunicação com o usuário. Nos campos de texto de Email e Senha, caso usuário entre com informações inválidas ou deixe os campos obrigatórios em branco são retornadas as seguintes mensagens de erro: "Email ou Senha inválidos", no caso de informações inválidas e "Preencha e-mail e senha para continuar!", caso deixe algum campo vazio. Se ocorrer algum dos erros citados os campos foram configurados para indicarem o erro através da mudança de cor.

![login](https://user-images.githubusercontent.com/31708472/58022491-f0586300-7ae3-11e9-8edf-e55fbb0ab4af.png)

Na página SignUp foram adicionados os feedfbacks de falha são compostos por: Caso o usuário deixe em branco os campos obrigatórios, entrar com nome de usuário inválido, e-mail informado já em uso, e a confirmação da senha não coincida com a senha informada. Caso usuário consiga efetuar o cadastro será mostrado um diálogo confirmando seu registro.

![registrar](https://user-images.githubusercontent.com/44438591/58040743-9750f500-7b0c-11e9-8a09-6c1aa314a4fd.png)
![usuario_criado](https://user-images.githubusercontent.com/44438591/58040832-daab6380-7b0c-11e9-86aa-a8e9f9fadfc6.png)

Na página EditProfile foram acrescentados os feedbacks caso o usuário deixe os campos obrigatórios em branco, se o usuário entrar com nome inválido. Se o perfil for alterado com sucesso um diálogo será exibido confirmando a alteração. 

![editar_perfil](https://user-images.githubusercontent.com/44438591/58041526-b05aa580-7b0e-11e9-9b67-6fcc83b790f9.png)

![sucesso_editar_perfil](https://user-images.githubusercontent.com/44438591/58041655-f7e13180-7b0e-11e9-8789-760be7261e86.png)

Na página RegisterMonitoring foram adicionados os feedbacks caso usuário não preencha os campos obrigatórios. Caso a criação da monitoria for efetuada um diálogo será exibido confirmando a criação da monitoria.

![registrar_monitoria](https://user-images.githubusercontent.com/44438591/58042072-13007100-7b10-11e9-908e-94af435abffe.png)
![sucesso_monitoria](https://user-images.githubusercontent.com/44438591/58042111-2b708b80-7b10-11e9-9dbc-ba4685ea2059.png)

Também foram atualizadas algumas estilizações das páginas para padronização indicada no projeto.

2019-05-21 00:37 UTC, caiooliv requested changes
É necessário correções visuais nas telas de sucesso de ação, como registro de monitoria, criação de usuário e edição de perfil.

2019-05-22 01:26 UTC, jpcirqueira commented
Foram ajustadas as mudanças visuais requisitadas.

Telas de sucesso de ação:

![usuario_criado_sucesso](https://user-images.githubusercontent.com/31708472/58140570-1b42d400-7c16-11e9-95c5-541c1027dbbb.png)

Tela de sucesso quando usuário é criado.

![sucesso_ monitoria](https://user-images.githubusercontent.com/31708472/58140590-2990f000-7c16-11e9-850f-ad0c149eb44b.png)

Tela de sucesso quando monitoria é criada.

![sucesso_edit](https://user-images.githubusercontent.com/31708472/58140619-4af1dc00-7c16-11e9-9b2f-8fc7325944a1.png)

Tela de sucesso quando perfil é editado.


Telas de feedback para erros:

![registrar](https://user-images.githubusercontent.com/31708472/58140737-c5baf700-7c16-11e9-8227-1ece20e7ce39.png)

Erro para nome invalido.

![cadastrar_monitoria](https://user-images.githubusercontent.com/31708472/58140744-cf445f00-7c16-11e9-9125-a8253e24b31a.png)

Erro quando campos obrigatórios não preenchidos.

![edit_perfil](https://user-images.githubusercontent.com/31708472/58140763-de2b1180-7c16-11e9-8686-550dbc175bd2.png)

Erro quando campos obrigatórios não preenchidos.

2019-05-22 18:02 UTC, LucasSiqz commented
Foram adicionados os novos testes criados na [branch](https://github.com/fga-eps-mds/2019.1-MaisMonitoria-FrontEnd/tree/REFACTOR-Testar-Frontend) utilizada para praticar os estudos dos testes.

2019-05-22 18:14 UTC, caiooliv approved these changes

2019-05-22 21:16 UTC, merged