Us26 formatacao das fotos
fga-eps-mds/2019.1-MaisMonitoria-FrontEnd pull request #33
Opened 2019-06-04 03:20 UTC by MatheusEstanislau

## Issue resolvida

[[US26] Fotos de Perfil](https://github.com/fga-eps-mds/2019.1-maismonitoria/issues/152)

## Comentário
Inicialmente foi limitado o formato das fotos dos usuários pela alteração do campo Accept aceitando fotos apenas nos formatos png e jpg.
![Captura de tela de 2019-06-04 00-07-45](https://user-images.githubusercontent.com/44438591/58848397-d3cc3700-865c-11e9-8e9c-5c13b9307bbe.png)

Após isso foram criadas as funções para realizar o preview e a função para apagar a foto previamente selecionada pelo usuário.
![Captura de tela de 2019-06-04 00-09-06](https://user-images.githubusercontent.com/44438591/58848473-260d5800-865d-11e9-8ade-4abd9cddeb85.png)
![Captura de tela de 2019-06-04 00-10-50](https://user-images.githubusercontent.com/44438591/58848506-44735380-865d-11e9-866b-0ddb5efa92dd.png)

![Captura de tela de 2019-06-04 00-06-19](https://user-images.githubusercontent.com/44438591/58848525-57862380-865d-11e9-9c29-69b7043b3d4f.png)

Na página Edit profile foram utilizados os mesmos métodos com pequenas distinções.
![Captura de tela de 2019-06-04 00-10-50](https://user-images.githubusercontent.com/44438591/58848701-ef840d00-865d-11e9-95f7-47695fedbcb9.png)
![Captura de tela de 2019-06-04 00-16-38](https://user-images.githubusercontent.com/44438591/58848756-12162600-865e-11e9-9472-f47be357fb44.png)

 
![Captura de tela de 2019-06-04 00-18-58](https://user-images.githubusercontent.com/44438591/58848847-63beb080-865e-11e9-949c-caa46f312dbd.png)

2019-06-04 18:57 UTC, lukassxp requested changes
A mensagem do PR está confusa, não consegui entender/ver as "pequenas mudanças" de um método para o outro, para mim parecem iguais(assim como os prints). Gostaria que vc descreva melhor oq foi implementado para poder decidir se o PR pode ser aprovado ou não. Outra questão que levanto é se já que os trechos de código são bastante parecidos, isso para não dizer idênticos, pq vc não optou por criar um novo componente ou mesmo reutilizar a função? Aguardo os esclarecimentos para finalizar a revisão.

2019-06-04 19:46 UTC, MatheusEstanislau commented
> A mensagem do PR está confusa, não consegui entender/ver as "pequenas mudanças" de um método para o outro, para mim parecem iguais(assim como os prints). Gostaria que vc descreva melhor oq foi implementado para poder decidir se o PR pode ser aprovado ou não. Outra questão que levanto é se já que os trechos de código são bastante parecidos, isso para não dizer idênticos, pq vc não optou por criar um novo componente ou mesmo reutilizar a função? Aguardo os esclarecimentos para finalizar a revisão.

No momento da produção do PR houve um equívoco com o print no editProfile, tal equivoco já foi corrigido adicionando o devido print.

As alterações de uma página para a outra foram os operadores ternários e mudanças no que seria renderizado caso o usuário não selecionasse alguma foto, pois no edit Profile já existe uma imagem pré-definida e não somente o preview como na página SignUP, preferi por não utilizar componentes pois foram utilizadas duas funções.

2019-06-04 23:33 UTC, caiooliv requested changes
Também é necessário mudanças visuais, o botão de remover foto da tela de edição de perfil deve ser corrigido para que mantenha o padrão visual da aplicação.

2019-06-05 19:17 UTC, MatheusEstanislau commented
> Também é necessário mudanças visuais, o botão de remover foto da tela de edição de perfil deve ser corrigido para que mantenha o padrão visual da aplicação.

Mudanças visuais solicitadas foram alteradas.

2019-06-05 19:40 UTC, lukassxp approved these changes

2019-06-05 19:43 UTC, lukassxp commented
> > A mensagem do PR está confusa, não consegui entender/ver as "pequenas mudanças" de um método para o outro, para mim parecem iguais(assim como os prints). Gostaria que vc descreva melhor oq foi implementado para poder decidir se o PR pode ser aprovado ou não. Outra questão que levanto é se já que os trechos de código são bastante parecidos, isso para não dizer idênticos, pq vc não optou por criar um novo componente ou mesmo reutilizar a função? Aguardo os esclarecimentos para finalizar a revisão.
> 
> No momento da produção do PR houve um equívoco com o print no editProfile, tal equivoco já foi corrigido adicionando o devido print.
> 
> As alterações de uma página para a outra foram os operadores ternários e mudanças no que seria renderizado caso o usuário não selecionasse alguma foto, pois no edit Profile já existe uma imagem pré-definida e não somente o preview como na página SignUP, preferi por não criar componentes pois foram utilizadas duas funções.

Ok, agora tive uma compreensão do que foi realizado, a solução atende oq foi solicitado na issue. Aguarde a revisão do PO sobre as alterações visuais solicitadas por ele.

2019-06-06 21:20 UTC, caiooliv approved these changes

2019-06-06 21:22 UTC, merged

2019-06-06 21:22 UTC, caiooliv commented
As mudanças foram atendidas e o PR será aceito