Ts20 cadastro no firebase sem cadastro no banco de dados
fga-eps-mds/2019.1-MaisMonitoria-FrontEnd pull request #37
Opened 2019-06-10 18:16 UTC by jpcirqueira

## Issue resolvida

[[TS20] Contas no firebase sem cadastro no banco de dados](https://github.com/fga-eps-mds/2019.1-MaisMonitoria/issues/161)

## Comentário

Para solução optamos por fazer uma validação na tela de login e também na tela de registro, esta validação procura o usuário atual no banco através do token  deste usuário. Caso o usuário esteja cadastrado no banco ele fara o registro e login normalmente, porem se o usuário não estiver cadastrado no banco aparecera um feedback de erro.

![image](https://user-images.githubusercontent.com/31708472/59216026-20e66680-8b91-11e9-83d8-83a5bb62fa6b.png)
Validação no SingUp.

![image](https://user-images.githubusercontent.com/31708472/59216159-6f940080-8b91-11e9-9cf4-0ca0c77ec3a0.png)
Validação no Login.

2019-06-18 01:45 UTC, caiooliv requested changes
É necessário correções de bugs e feedback das informações. Ao encontrar o usuário no firebase e não no banco a mensagem está errada, atualmente ela está assim :
![image](https://user-images.githubusercontent.com/23109243/59647283-faa46600-9150-11e9-990c-633090f3b87f.png)
 é necessário mudanças para que seja mais agrádavel para o usuário como "Erro ao realizar operação, tente novamente". Além da correção de Bugs, quando o usuário é removido da base do firebase ao tentar cadastrar novamente a aplicação não permite, diz que o email está em uso

2019-06-20 14:13 UTC, jpcirqueira commented
foram feitas mudanças nas validações, para que o usuário não consiga fazer o login no firebase e não cadastrar no banco, também foi alterado a mensagem de feedback para o usuário.

2019-06-21 16:38 UTC, matheus-rn commented
Foi identificado que não há tratamento de erro ao deletar o usuário. Linhas 148 á 152.

2019-06-22 02:10 UTC, matheus-rn commented
A solução foi analisada e aprovada.

2019-06-22 02:10 UTC, merged