REFACTOR-Campos criar / editar monitoria
fga-eps-mds/2019.1-MaisMonitoria-FrontEnd pull request #42
Opened 2019-06-15 21:12 UTC by MoacirMSJ

## Issue resolvida

#172- [REFACTOR-Campos criar / editar monitoria](https://github.com/fga-eps-mds/2019.1-MaisMonitoria/issues/172)

## Comentário
Foi alterado os campos da pagina de editar monitoria para que ficasse semelhante aos campos de registrar uma nova monitoria. 
 
Registrar Monitoria:
![image](https://user-images.githubusercontent.com/48539765/59556385-35af6980-8f98-11e9-8c53-c9f7d8e7ad74.png)

Editar Monitoria:
![image](https://user-images.githubusercontent.com/48539765/59556440-f33a5c80-8f98-11e9-82ca-495bc1173d80.png)

2019-06-17 14:13 UTC, caiooliv commented
Apesar de não fazer parte dos critérios de aceitação, acho uma refatoração válida o link de abrir a conversa no telegram seja aberto em uma nova aba, para que o usuário não feche a aplicação para iniciar a conversa com o monitor. Avalie a sugestão de refatoração.

2019-06-18 02:59 UTC, caiooliv requested changes
Os campos de descrição de monitoria não estão em um padrão, para criar monitoria é uma caixa de texto enquanto na edição de monitoria não, outro ponto importante de ressaltar é que no perfil do usuário também há um link para iniciar uma conversa no telegram, e não é inciada a conversa em outra aba.
Com a adição de iniciar a conversa em outra aba um warning apareceu no projeto, indicando uma possível falha de segurança, para resolver esse warning acesse o link [https://mathiasbynens.github.io/rel-noopener/](https://mathiasbynens.github.io/rel-noopener/) , para mais informações.

2019-06-18 04:31 UTC, MoacirMSJ commented
foram efetuadas as mudanças do campo de descrição e a falha de segurança ao abrir outra aba.

2019-06-20 01:06 UTC, MoacirMSJ commented
Realizada a mudança no ProfileMonitor para evitar a falha de segurança.

2019-06-20 01:22 UTC, caiooliv requested changes
O campo de descrição da monitoria não está como obrigatório no momento do cadastro da monitora, esse campo deve ser obrigatório e conter uma indicação visual que é obrigatório, como o asterisco ao lado do nome do campo.

2019-06-20 14:22 UTC, caiooliv approved these changes

2019-06-20 14:22 UTC, merged